# Semantic Cache Configuration
server:
  port: ":8080"
  host: "localhost"

redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  max_retries: 3
  pool_size: 10

cache:
  prefix: "semantic_cache"
  threshold: 0.8
  max_cache_size: 10000
  enable_lru: true
  cleanup_interval: "1h"
  embedding_cache_size: 1000

embedding:
  url: "http://localhost:11434/api/embeddings"
  model: "nomic-embed-text"
  timeout: "30s"
  max_retries: 3

# Error handling and resilience
error_handling:
  max_retries: 3
  retry_base_delay: "100ms"
  retry_max_delay: "5s"
  retry_multiplier: 2.0

# Circuit breaker configuration
circuit_breaker:
  timeout: "1m"
  max_failures: 5
  half_open_max_calls: 3

logging:
  level: "info"
  format: "json"

monitoring:
  enable_metrics: true
  metrics_path: "/metrics"
  health_check_interval: "30s"
